//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentByService
    {
        public int id_DocumentlyByService { get; set; }
        public int id_ClientService { get; set; }
        public string DocumentPath { get; set; }
    
        public virtual ClientService ClientService { get; set; }
    }
}
